import { Formation, Badge, Notification } from '../types';

export const mockFormations: Formation[] = [
  {
    id: '1',
    title: 'Techniques de barbe professionnelles',
    description: 'Maîtrisez l\'art de la taille de barbe avec les techniques les plus avancées du métier. Apprenez à créer des formes parfaites et à utiliser les outils professionnels.',
    category: 'barbier',
    level: 'intermediaire',
    price: 149,
    duration: 8,
    formateurId: '1',
    formateur: {
      name: 'Marc Dubois',
      photo: '',
      rating: 4.9,
    },
    thumbnailUrl: '',
    modules: [
      {
        id: '1-1',
        title: 'Introduction aux outils de barbe',
        description: 'Découvrez les différents outils et leur utilisation',
        videoUrl: '',
        duration: 45,
        order: 1,
      },
      {
        id: '1-2',
        title: 'Techniques de taille avancées',
        description: 'Maîtrisez les techniques de taille professionnelles',
        videoUrl: '',
        duration: 60,
        order: 2,
      },
    ],
    rating: 4.8,
    reviewCount: 127,
    enrolledCount: 340,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Coupe dégradée moderne',
    description: 'Apprenez les dernières tendances en matière de coupe dégradée et fade. Techniques modernes pour des résultats professionnels.',
    category: 'barbier',
    level: 'avance',
    price: 199,
    duration: 12,
    formateurId: '2',
    formateur: {
      name: 'Sarah Martin',
      photo: '',
      rating: 4.7,
    },
    thumbnailUrl: '',
    modules: [
      {
        id: '2-1',
        title: 'Bases du dégradé',
        description: 'Comprendre les principes du dégradé',
        videoUrl: '',
        duration: 50,
        order: 1,
      },
      {
        id: '2-2',
        title: 'Techniques de fade avancées',
        description: 'Maîtrisez les fades complexes',
        videoUrl: '',
        duration: 70,
        order: 2,
      },
    ],
    rating: 4.6,
    reviewCount: 89,
    enrolledCount: 256,
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    title: 'Bases de la mécanique automobile',
    description: 'Introduction complète aux principes fondamentaux de la mécanique automobile. Parfait pour débuter dans le domaine.',
    category: 'mecanique',
    level: 'debutant',
    price: 299,
    duration: 20,
    formateurId: '3',
    formateur: {
      name: 'Pierre Leblanc',
      photo: '',
      rating: 4.8,
    },
    thumbnailUrl: '',
    modules: [
      {
        id: '3-1',
        title: 'Introduction aux moteurs',
        description: 'Comprendre le fonctionnement des moteurs',
        videoUrl: '',
        duration: 90,
        order: 1,
      },
      {
        id: '3-2',
        title: 'Systèmes de transmission',
        description: 'Découvrir les systèmes de transmission',
        videoUrl: '',
        duration: 85,
        order: 2,
      },
    ],
    rating: 4.7,
    reviewCount: 203,
    enrolledCount: 445,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    title: 'Électricité résidentielle avancée',
    description: 'Techniques avancées d\'installation électrique pour les projets résidentiels. Sécurité et normes incluses.',
    category: 'electricite',
    level: 'avance',
    price: 399,
    duration: 16,
    formateurId: '4',
    formateur: {
      name: 'Jean Électro',
      photo: '',
      rating: 4.9,
    },
    thumbnailUrl: '',
    modules: [
      {
        id: '4-1',
        title: 'Normes et sécurité',
        description: 'Respecter les normes de sécurité électrique',
        videoUrl: '',
        duration: 75,
        order: 1,
      },
      {
        id: '4-2',
        title: 'Installation de panneaux',
        description: 'Installer des panneaux électriques',
        videoUrl: '',
        duration: 120,
        order: 2,
      },
    ],
    rating: 4.9,
    reviewCount: 156,
    enrolledCount: 312,
    createdAt: '2024-01-10',
  },
  {
    id: '5',
    title: 'Coiffure créative et tendances',
    description: 'Explorez les techniques de coiffure créative et les dernières tendances. Développez votre style unique.',
    category: 'barbier',
    level: 'intermediaire',
    price: 179,
    duration: 10,
    formateurId: '5',
    formateur: {
      name: 'Sophie Style',
      photo: '',
      rating: 4.6,
    },
    thumbnailUrl: '',
    modules: [
      {
        id: '5-1',
        title: 'Tendances actuelles',
        description: 'Découvrir les tendances du moment',
        videoUrl: '',
        duration: 55,
        order: 1,
      },
      {
        id: '5-2',
        title: 'Techniques créatives',
        description: 'Développer sa créativité',
        videoUrl: '',
        duration: 65,
        order: 2,
      },
    ],
    rating: 4.5,
    reviewCount: 92,
    enrolledCount: 198,
    createdAt: '2024-02-15',
  },
];

export const mockBadges: Badge[] = [
  {
    id: 'badge-1',
    name: 'Premier pas',
    description: 'Complété votre première formation',
    icon: 'trophy',
    criteria: 'Complete 1 formation',
    rarity: 'common',
  },
  {
    id: 'badge-2',
    name: 'Étudiant assidu',
    description: 'Complété 5 formations',
    icon: 'star',
    criteria: 'Complete 5 formations',
    rarity: 'rare',
  },
  {
    id: 'badge-3',
    name: 'Expert barbier',
    description: 'Maîtrisé toutes les formations barbier',
    icon: 'crown',
    criteria: 'Complete all barber courses',
    rarity: 'epic',
  },
  {
    id: 'badge-4',
    name: 'Mentor',
    description: 'Aidé 10 autres étudiants',
    icon: 'people',
    criteria: 'Help 10 students',
    rarity: 'legendary',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    profileId: 'user-1',
    title: 'Nouvelle formation disponible',
    message: 'La formation "Techniques de barbe professionnelles" est maintenant disponible !',
    type: 'info',
    read: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    profileId: 'user-1',
    title: 'Formation terminée',
    message: 'Félicitations ! Vous avez terminé la formation "Coupe dégradée moderne".',
    type: 'success',
    read: false,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif-3',
    profileId: 'user-1',
    title: 'Nouveau badge gagné',
    message: 'Vous avez gagné le badge "Étudiant assidu" !',
    type: 'success',
    read: true,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
  },
];